#!/usr/bin/env python3
"""Generate publication-quality poster figures for SpermNet.

Produces 8 high-resolution figures suitable for academic posters, using data
already generated by the SpermNet pipeline (outputs/ directory).

Usage:
    python generate_poster_figures.py            # generate all figures
    python generate_poster_figures.py --out DIR   # custom output directory

Outputs are saved to ``outputs/poster_figures/`` by default (300 dpi PNG).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.patheffects as path_effects
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats

import config

# ---------------------------------------------------------------------------
# Style constants
# ---------------------------------------------------------------------------
POSTER_DPI = 300
FONT_FAMILY = "sans-serif"

# Consistent colour palette for motility classes
CLASS_COLORS = {
    "Progressive":     "#2ecc71",   # vibrant green
    "Non-progressive": "#f39c12",   # warm amber
    "Immotile":        "#e74c3c",   # vivid red
}

# Modern background tint for figures
BG_COLOR = "#fafafa"
GRID_COLOR = "#dddddd"

# Detector palette for ablation figures
DETECTOR_COLORS = [
    "#3498db",  # blue
    "#e74c3c",  # red
    "#2ecc71",  # green
    "#9b59b6",  # purple
    "#f39c12",  # amber
    "#1abc9c",  # teal
    "#e67e22",  # orange
    "#34495e",  # dark grey
    "#16a085",  # sea green
    "#c0392b",  # dark red
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _apply_poster_style():
    """Set global matplotlib parameters for poster aesthetics."""
    plt.rcParams.update({
        "font.family": FONT_FAMILY,
        "font.size": 13,
        "axes.titlesize": 16,
        "axes.labelsize": 14,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
        "legend.fontsize": 11,
        "figure.facecolor": BG_COLOR,
        "axes.facecolor": "#ffffff",
        "axes.edgecolor": "#cccccc",
        "axes.grid": True,
        "grid.color": GRID_COLOR,
        "grid.alpha": 0.5,
        "grid.linewidth": 0.5,
    })


def _save(fig, path: Path, tight: bool = True):
    """Save figure with consistent settings."""
    if tight:
        fig.savefig(path, dpi=POSTER_DPI, bbox_inches="tight",
                    facecolor=fig.get_facecolor(), pad_inches=0.3)
    else:
        fig.savefig(path, dpi=POSTER_DPI, facecolor=fig.get_facecolor())
    plt.close(fig)
    print(f"  ✓ Saved {path.name}")


def _load_all_motility() -> pd.DataFrame:
    """Load motility CSVs from all 20 videos."""
    frames = []
    for csv_path in sorted(config.EVENTS_OUT.glob("*_motility.csv")):
        df = pd.read_csv(csv_path)
        vid = csv_path.stem.replace("_motility", "")
        df["video"] = vid
        frames.append(df)
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)


def _load_all_summaries() -> pd.DataFrame:
    """Load summary JSONs from all 20 videos."""
    rows = []
    for json_path in sorted(config.EVENTS_OUT.glob("*_summary.json")):
        with open(json_path) as f:
            rows.append(json.load(f))
    if not rows:
        return pd.DataFrame()
    return pd.DataFrame(rows)


# ═══════════════════════════════════════════════════════════════════════════
# Figure 1 – Pipeline Architecture Diagram
# ═══════════════════════════════════════════════════════════════════════════

def fig1_pipeline_diagram(out_dir: Path):
    """Programmatic pipeline flow-chart."""
    fig, ax = plt.subplots(figsize=(16, 5))
    ax.set_xlim(0, 16)
    ax.set_ylim(0, 5)
    ax.axis("off")
    fig.patch.set_facecolor(BG_COLOR)

    # Pipeline stages
    stages = [
        ("Video\nInput",             "#3498db", "V", 1.0),
        ("Frame\nExtraction",        "#2980b9", "F",  3.2),
        ("YOLOv8\nDetection",        "#8e44ad", "D", 5.4),
        ("BoT-SORT\nTracking",       "#2c3e50", "T", 7.6),
        ("WHO 2021\nKinematics",     "#27ae60", "K", 9.8),
        ("Motility\nClassification", "#e67e22", "C",  12.0),
        ("Clinical\nReport + LLM",   "#c0392b", "R", 14.2),
    ]

    box_w, box_h = 1.8, 2.2
    y_center = 2.5

    for label, color, icon, x_center in stages:
        # Draw rounded box
        box = FancyBboxPatch(
            (x_center - box_w / 2, y_center - box_h / 2), box_w, box_h,
            boxstyle="round,pad=0.15", facecolor=color, edgecolor="white",
            linewidth=2, alpha=0.92,
        )
        ax.add_patch(box)

        # Icon letter in circle
        ax.text(x_center, y_center + 0.35, icon, ha="center", va="center",
                fontsize=20, fontweight="bold", color="white",
                family="monospace")

        # Label
        txt = ax.text(x_center, y_center - 0.4, label, ha="center",
                      va="center", fontsize=10, fontweight="bold",
                      color="white", linespacing=1.3)
        txt.set_path_effects([
            path_effects.withStroke(linewidth=2, foreground=color)])

    # Arrows between boxes
    for i in range(len(stages) - 1):
        x1 = stages[i][3] + box_w / 2 + 0.05
        x2 = stages[i + 1][3] - box_w / 2 - 0.05
        ax.annotate("", xy=(x2, y_center), xytext=(x1, y_center),
                    arrowprops=dict(arrowstyle="-|>", color="#555555",
                                    lw=2.5, mutation_scale=18))

    # Title
    ax.text(8, 4.7, "SpermNet — Automated Sperm Motility Analysis Pipeline",
            ha="center", va="center", fontsize=17, fontweight="bold",
            color="#2c3e50")

    # Bottom annotations
    annotations = [
        (1.0,  "50 fps, 640×480"),
        (3.2,  "JPEG frames"),
        (5.4,  "3 classes"),
        (7.6,  "Multi-object"),
        (9.8,  "8 parameters"),
        (12.0, "P / NP / Im"),
        (14.2, "GPT-4o / Claude"),
    ]
    for x, text in annotations:
        ax.text(x, y_center - box_h / 2 - 0.35, text, ha="center",
                va="top", fontsize=8, color="#666666", style="italic")

    _save(fig, out_dir / "fig1_pipeline_architecture.png")


# ═══════════════════════════════════════════════════════════════════════════
# Figure 2 – Cohort Motility Stacked Bar Chart
# ═══════════════════════════════════════════════════════════════════════════

def fig2_cohort_motility(out_dir: Path):
    """Stacked horizontal bar chart showing motility distribution per video."""
    summaries = _load_all_summaries()
    if summaries.empty:
        print("  ⚠ No summary data found – skipping fig2")
        return

    summaries = summaries.sort_values("video", key=lambda s: s.astype(int))

    videos = summaries["video"].astype(str).tolist()
    prog = summaries["progressive_pct"].values
    np_vals = summaries["non_progressive_pct"].values
    imm = summaries["immotile_pct"].values

    fig, ax = plt.subplots(figsize=(10, 7))

    y = np.arange(len(videos))
    bar_h = 0.65

    ax.barh(y, prog, height=bar_h, color=CLASS_COLORS["Progressive"],
            label="Progressive", edgecolor="white", linewidth=0.5)
    ax.barh(y, np_vals, height=bar_h, left=prog,
            color=CLASS_COLORS["Non-progressive"],
            label="Non-progressive", edgecolor="white", linewidth=0.5)
    ax.barh(y, imm, height=bar_h, left=prog + np_vals,
            color=CLASS_COLORS["Immotile"],
            label="Immotile", edgecolor="white", linewidth=0.5)

    # WHO reference lines
    ax.axvline(42, color="#555555", ls="--", lw=1.2, alpha=0.7)
    ax.text(42.5, len(videos) - 0.3, "WHO total\nmotility ≥ 42 %",
            fontsize=8, color="#555555", va="top")
    ax.axvline(30, color="#888888", ls=":", lw=1.0, alpha=0.6)
    ax.text(30.5, len(videos) - 0.3, "WHO prog.\n≥ 30 %",
            fontsize=8, color="#888888", va="top")

    ax.set_yticks(y)
    ax.set_yticklabels([f"Video {v}" for v in videos])
    ax.set_xlabel("Percentage (%)", fontweight="bold")
    ax.set_xlim(0, 100)
    ax.invert_yaxis()
    ax.legend(loc="lower right", framealpha=0.9, edgecolor="#cccccc")
    ax.set_title("Motility Distribution Across 20 VISEM Videos",
                 fontweight="bold", pad=12)

    # Track count annotations
    for i, (v, t) in enumerate(
            zip(videos, summaries["total_tracks"].values)):
        ax.text(101, i, f"n={int(t)}", va="center", fontsize=8,
                color="#666666")

    _save(fig, out_dir / "fig2_cohort_motility_bars.png")


# ═══════════════════════════════════════════════════════════════════════════
# Figure 3 – WHO Kinematic Violin Plots
# ═══════════════════════════════════════════════════════════════════════════

def fig3_kinematic_violins(out_dir: Path):
    """Violin + strip plots of kinematic parameters by motility class."""
    all_mot = _load_all_motility()
    if all_mot.empty:
        print("  ⚠ No motility data found – skipping fig3")
        return

    # Standardise motility labels
    label_map = {
        "progressive": "Progressive",
        "non_progressive": "Non-progressive",
        "immotile": "Immotile",
    }
    all_mot["Motility"] = all_mot["motility"].map(label_map)
    all_mot = all_mot.dropna(subset=["Motility"])

    metrics = [
        ("VCL", "VCL (µm/s)\nCurvilinear Velocity"),
        ("VSL", "VSL (µm/s)\nStraight-line Velocity"),
        ("VAP", "VAP (µm/s)\nAverage-path Velocity"),
        ("LIN", "LIN (ratio)\nLinearity"),
        ("STR", "STR (ratio)\nStraightness"),
    ]

    fig, axes = plt.subplots(1, 5, figsize=(20, 5.5))

    order = ["Progressive", "Non-progressive", "Immotile"]
    palette = [CLASS_COLORS[c] for c in order]

    for ax, (col, ylabel) in zip(axes, metrics):
        if col not in all_mot.columns:
            ax.set_visible(False)
            continue

        sns.violinplot(data=all_mot, x="Motility", y=col, hue="Motility",
                       order=order, hue_order=order,
                       palette=palette, inner=None, cut=0, ax=ax, alpha=0.35,
                       linewidth=0, legend=False)
        sns.stripplot(data=all_mot, x="Motility", y=col, hue="Motility",
                      order=order, hue_order=order,
                      palette=palette, size=2.5, alpha=0.5, jitter=0.25,
                      ax=ax, linewidth=0, legend=False)
        sns.boxplot(data=all_mot, x="Motility", y=col, hue="Motility",
                    order=order, hue_order=order,
                    palette=palette, width=0.15, fliersize=0, ax=ax,
                    linewidth=1.2, boxprops=dict(alpha=0.7), legend=False)

        ax.set_xlabel("")
        ax.set_ylabel(ylabel, fontsize=10)
        ax.tick_params(axis="x", rotation=25)

    fig.suptitle("WHO Kinematic Parameters by Motility Class (n = {:,} tracks)"
                 .format(len(all_mot)),
                 fontweight="bold", fontsize=15, y=1.02)
    fig.tight_layout()
    _save(fig, out_dir / "fig3_kinematic_violins.png")


# ═══════════════════════════════════════════════════════════════════════════
# Figure 4 – Predicted vs Ground Truth Correlation
# ═══════════════════════════════════════════════════════════════════════════

def fig4_gt_correlation(out_dir: Path):
    """Three-panel scatter plot of predicted vs clinical ground truth."""
    gt_csv = config.OUTPUTS_DIR / "evaluation" / "gt_comparison.csv"
    if not gt_csv.exists():
        print("  ⚠ gt_comparison.csv not found – skipping fig4")
        return

    merged = pd.read_csv(gt_csv)

    categories = [
        ("gt_progressive", "pred_progressive", "Progressive", CLASS_COLORS["Progressive"]),
        ("gt_non_progressive", "pred_non_progressive", "Non-progressive", CLASS_COLORS["Non-progressive"]),
        ("gt_immotile", "pred_immotile", "Immotile", CLASS_COLORS["Immotile"]),
    ]

    fig, axes = plt.subplots(1, 3, figsize=(16, 5.5))

    for ax, (gt_col, pr_col, title, color) in zip(axes, categories):
        gt = merged[gt_col].values
        pr = merged[pr_col].values

        # Identity line
        lim = max(gt.max(), pr.max()) + 5
        ax.plot([0, lim], [0, lim], "--", color="#aaaaaa", lw=1.2,
                label="Perfect agreement", zorder=1)

        # Scatter
        ax.scatter(gt, pr, s=70, c=color, edgecolors="white", linewidth=0.8,
                   alpha=0.85, zorder=3)

        # Regression line
        if len(gt) > 2:
            slope, intercept, r_val, p_val, _ = stats.linregress(gt, pr)
            x_fit = np.linspace(0, lim, 100)
            ax.plot(x_fit, slope * x_fit + intercept, "-", color=color,
                    lw=2, alpha=0.7, zorder=2)
            # Annotation box
            txt = f"r = {r_val:.3f}\np = {p_val:.4f}"
            ax.text(0.05, 0.95, txt, transform=ax.transAxes, fontsize=10,
                    va="top", ha="left",
                    bbox=dict(boxstyle="round,pad=0.4", facecolor="white",
                              edgecolor=color, alpha=0.85))

        # Video labels
        if "video" in merged.columns:
            for _, row in merged.iterrows():
                ax.annotate(str(int(row["video"])),
                            (row[gt_col], row[pr_col]),
                            fontsize=7, alpha=0.55, ha="center",
                            va="bottom", xytext=(0, 4),
                            textcoords="offset points")

        ax.set_xlim(0, lim)
        ax.set_ylim(0, lim)
        ax.set_aspect("equal")
        ax.set_xlabel("Clinical Ground Truth (%)", fontweight="bold")
        ax.set_ylabel("SpermNet Predicted (%)", fontweight="bold")
        ax.set_title(title, fontweight="bold", color=color, fontsize=14)
        ax.legend(loc="lower right", fontsize=9, framealpha=0.8)

    fig.suptitle("Pipeline Predictions vs Clinical Semen Analysis (n = 20 videos)",
                 fontweight="bold", fontsize=15, y=1.03)
    fig.tight_layout()
    _save(fig, out_dir / "fig4_gt_correlation.png")


# ═══════════════════════════════════════════════════════════════════════════
# Figure 5 – Temporal Dynamics
# ═══════════════════════════════════════════════════════════════════════════

def fig5_temporal_dynamics(out_dir: Path):
    """Enhanced stacked area chart of motility evolution over time."""
    agg_csv = config.TEMPORAL_OUT / "temporal_aggregate.csv"
    if not agg_csv.exists():
        print("  ⚠ temporal_aggregate.csv not found – skipping fig5")
        return

    agg = pd.read_csv(agg_csv)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5.5))

    # --- Left: Stacked area ---
    t = agg["t_mid_s"].values
    prog = agg["pct_Progressive_mean"].values
    np_m = agg["pct_Non-progressive_mean"].values
    imm = agg["pct_Immotile_mean"].values

    ax1.fill_between(t, 0, prog, color=CLASS_COLORS["Progressive"],
                     alpha=0.85, label="Progressive")
    ax1.fill_between(t, prog, prog + np_m,
                     color=CLASS_COLORS["Non-progressive"],
                     alpha=0.85, label="Non-progressive")
    ax1.fill_between(t, prog + np_m, prog + np_m + imm,
                     color=CLASS_COLORS["Immotile"],
                     alpha=0.85, label="Immotile")

    ax1.set_xlim(t.min(), t.max())
    ax1.set_ylim(0, 100)
    ax1.set_xlabel("Time (seconds)", fontweight="bold")
    ax1.set_ylabel("Proportion (%)", fontweight="bold")
    ax1.set_title("(a) Temporal Motility Distribution", fontweight="bold")
    ax1.legend(loc="upper right", framealpha=0.9, edgecolor="#cccccc")

    # --- Right: Line + CI bands ---
    for state, col_mean, col_std in [
        ("Progressive", "pct_Progressive_mean", "pct_Progressive_std"),
        ("Non-progressive", "pct_Non-progressive_mean", "pct_Non-progressive_std"),
        ("Immotile", "pct_Immotile_mean", "pct_Immotile_std"),
    ]:
        mean = agg[col_mean].values
        std = agg[col_std].values
        color = CLASS_COLORS[state]
        ax2.plot(t, mean, "-o", color=color, lw=2.5, markersize=6,
                 label=state, zorder=3)
        ax2.fill_between(t, mean - std, mean + std, color=color, alpha=0.15,
                         zorder=1)

    ax2.set_xlim(t.min(), t.max())
    ax2.set_ylim(0, 100)
    ax2.set_xlabel("Time (seconds)", fontweight="bold")
    ax2.set_ylabel("Mean Proportion ± 1 SD (%)", fontweight="bold")
    ax2.set_title("(b) Temporal Trends with Variability", fontweight="bold")
    ax2.legend(loc="upper right", framealpha=0.9, edgecolor="#cccccc")

    fig.suptitle("Motility Dynamics Over 30-Second Recording Window (n = 20 videos)",
                 fontweight="bold", fontsize=15, y=1.03)
    fig.tight_layout()
    _save(fig, out_dir / "fig5_temporal_dynamics.png")


# ═══════════════════════════════════════════════════════════════════════════
# Figure 6 – Markov State Transition Heatmap
# ═══════════════════════════════════════════════════════════════════════════

def fig6_markov_transitions(out_dir: Path):
    """Enhanced Markov transition matrix heatmap + stationary distribution."""
    tm_csv = config.MARKOV_OUT / "transition_matrix.csv"
    if not tm_csv.exists():
        print("  ⚠ transition_matrix.csv not found – skipping fig6")
        return

    T = pd.read_csv(tm_csv, index_col=0)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5),
                                    gridspec_kw={"width_ratios": [2, 1]})

    # --- Left: Transition heatmap ---
    labels = ["Progressive", "Non-progressive", "Immotile"]
    short = ["P", "NP", "Im"]

    sns.heatmap(T.values, annot=True, fmt=".4f", cmap="YlOrRd",
                vmin=0, vmax=1, linewidths=2, linecolor="white",
                xticklabels=short, yticklabels=short,
                cbar_kws={"label": "Transition Probability"},
                ax=ax1, square=True)
    ax1.set_xlabel("To State", fontweight="bold")
    ax1.set_ylabel("From State", fontweight="bold")
    ax1.set_title("(a) State Transition Matrix", fontweight="bold")

    # Highlight diagonal (self-transitions)
    for i in range(3):
        ax1.add_patch(plt.Rectangle((i, i), 1, 1, fill=False,
                                     edgecolor="#2c3e50", lw=2.5))

    # --- Right: Stationary distribution ---
    # Compute stationary distribution from T
    T_arr = T.values.astype(float)
    eigenvalues, eigenvectors = np.linalg.eig(T_arr.T)
    idx = np.argmin(np.abs(eigenvalues - 1.0))
    pi = np.real(eigenvectors[:, idx])
    pi = pi / pi.sum()

    colors = [CLASS_COLORS[s] for s in labels]
    bars = ax2.bar(short, pi * 100, color=colors, edgecolor="white",
                   linewidth=1.5, width=0.6)

    for bar, val in zip(bars, pi * 100):
        ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1.5,
                 f"{val:.1f}%", ha="center", fontweight="bold", fontsize=12)

    ax2.set_ylim(0, max(pi * 100) + 12)
    ax2.set_ylabel("Equilibrium Occupancy (%)", fontweight="bold")
    ax2.set_title("(b) Stationary Distribution", fontweight="bold")

    fig.suptitle("Markov Chain Analysis of Motility State Transitions",
                 fontweight="bold", fontsize=15, y=1.03)
    fig.tight_layout()
    _save(fig, out_dir / "fig6_markov_transitions.png")


# ═══════════════════════════════════════════════════════════════════════════
# Figure 7 – Multi-Model Ablation Comparison
# ═══════════════════════════════════════════════════════════════════════════

def fig7_model_comparison(out_dir: Path):
    """Grouped bar chart comparing MAE across detector × tracker combos."""
    metrics_json = (config.OUTPUTS_DIR / "evaluation_ablation"
                    / "multi_model_metrics.json")
    if not metrics_json.exists():
        print("  ⚠ multi_model_metrics.json not found – skipping fig7")
        return

    with open(metrics_json) as f:
        all_metrics = json.load(f)

    # Select most interesting experiments (prioritise bytetrack variants)
    preferred = [
        "yolov8n_bytetrack", "yolov8l_bytetrack",
        "yolov9t_bytetrack", "yolo11n_bytetrack",
        "rtdetr-l_bytetrack",
        "yolov8n_botsort", "yolov8l_botsort",
    ]
    experiments = [e for e in preferred if e in all_metrics]
    if not experiments:
        experiments = list(all_metrics.keys())[:8]

    categories = ["progressive", "non_progressive", "immotile"]
    cat_labels = ["Progressive", "Non-progressive", "Immotile"]

    n_exp = len(experiments)
    n_cat = len(categories)
    x = np.arange(n_cat)
    width = 0.8 / n_exp

    fig, ax = plt.subplots(figsize=(14, 6))

    for i, exp in enumerate(experiments):
        mae_vals = [all_metrics[exp].get(cat, {}).get("MAE", 0)
                    for cat in categories]
        offset = (i - n_exp / 2 + 0.5) * width
        bars = ax.bar(x + offset, mae_vals, width * 0.9,
                      color=DETECTOR_COLORS[i % len(DETECTOR_COLORS)],
                      edgecolor="white", linewidth=0.5,
                      label=exp.replace("_", " + ").title(), alpha=0.88)
        # Value labels on top
        for bar, val in zip(bars, mae_vals):
            if val > 0:
                ax.text(bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + 0.4,
                        f"{val:.1f}", ha="center", va="bottom",
                        fontsize=7, fontweight="bold")

    ax.set_xticks(x)
    ax.set_xticklabels(cat_labels, fontweight="bold")
    ax.set_ylabel("Mean Absolute Error (%)", fontweight="bold")
    ax.set_title("Detector × Tracker Ablation — MAE vs Clinical Ground Truth",
                 fontweight="bold", pad=12)
    ax.legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=9,
              framealpha=0.9, edgecolor="#cccccc")
    ax.set_ylim(0)

    fig.tight_layout()
    _save(fig, out_dir / "fig7_model_comparison.png")


# ═══════════════════════════════════════════════════════════════════════════
# Figure 8 – WHO Compliance Donut + Cohort Summary
# ═══════════════════════════════════════════════════════════════════════════

def fig8_who_compliance(out_dir: Path):
    """Donut chart of overall cohort motility + WHO compliance gauge."""
    summaries = _load_all_summaries()
    if summaries.empty:
        print("  ⚠ No summary data found – skipping fig8")
        return

    # Weighted averages (weighted by total_tracks)
    weights = summaries["total_tracks"].values.astype(float)
    total = weights.sum()
    w_prog = np.average(summaries["progressive_pct"].values, weights=weights)
    w_np = np.average(summaries["non_progressive_pct"].values, weights=weights)
    w_imm = np.average(summaries["immotile_pct"].values, weights=weights)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    # --- Left: Donut chart ---
    sizes = [w_prog, w_np, w_imm]
    labels_pie = ["Progressive\n{:.1f}%".format(w_prog),
                  "Non-progressive\n{:.1f}%".format(w_np),
                  "Immotile\n{:.1f}%".format(w_imm)]
    colors = [CLASS_COLORS["Progressive"],
              CLASS_COLORS["Non-progressive"],
              CLASS_COLORS["Immotile"]]

    wedges, texts = ax1.pie(
        sizes, labels=labels_pie, colors=colors,
        startangle=90, wedgeprops=dict(width=0.45, edgecolor="white",
                                       linewidth=3),
        textprops=dict(fontsize=12, fontweight="bold"))

    # Centre text
    ax1.text(0, 0, f"n = {int(total)}\ntracks",
             ha="center", va="center", fontsize=14,
             fontweight="bold", color="#2c3e50")
    ax1.set_title("(a) Weighted Cohort Distribution", fontweight="bold",
                  fontsize=14, pad=15)

    # --- Right: WHO Compliance bars ---
    total_motility = w_prog + w_np
    metrics = [
        ("Total Motility\n(P + NP)", total_motility, 42.0, "#3498db"),
        ("Progressive\nMotility", w_prog, 30.0, CLASS_COLORS["Progressive"]),
        ("Immotile", w_imm, 58.0, CLASS_COLORS["Immotile"]),
    ]

    y_pos = np.arange(len(metrics))
    for i, (label, val, who_ref, color) in enumerate(metrics):
        bar = ax2.barh(i, val, height=0.5, color=color, alpha=0.85,
                       edgecolor="white", linewidth=1.5)
        ax2.text(val + 1.5, i, f"{val:.1f}%", va="center", fontsize=12,
                 fontweight="bold", color=color)

        # WHO reference marker
        ax2.plot(who_ref, i, "D", color="#2c3e50", markersize=10, zorder=5)
        # Compliance check
        if label.startswith("Immotile"):
            status = "✓" if val <= who_ref else "✗"
        else:
            status = "✓" if val >= who_ref else "✗"
        ax2.text(who_ref, i + 0.35, f"WHO: {who_ref:.0f}% {status}",
                 ha="center", fontsize=9, color="#2c3e50", fontweight="bold")

    ax2.set_yticks(y_pos)
    ax2.set_yticklabels([m[0] for m in metrics], fontsize=11)
    ax2.set_xlim(0, 100)
    ax2.set_xlabel("Percentage (%)", fontweight="bold")
    ax2.set_title("(b) WHO 2021 Reference Compliance", fontweight="bold",
                  fontsize=14, pad=15)
    ax2.invert_yaxis()

    fig.suptitle("Cohort-Level Motility Summary — 20 VISEM Videos",
                 fontweight="bold", fontsize=15, y=1.02)
    fig.tight_layout()
    _save(fig, out_dir / "fig8_who_compliance.png")


# ═══════════════════════════════════════════════════════════════════════════
# Main entry point
# ═══════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Generate poster-quality figures for SpermNet.")
    parser.add_argument("--out", type=str, default=None,
                        help="Output directory (default: outputs/poster_figures)")
    args = parser.parse_args()

    out_dir = Path(args.out) if args.out else config.OUTPUTS_DIR / "poster_figures"
    out_dir.mkdir(parents=True, exist_ok=True)

    _apply_poster_style()

    print("═" * 60)
    print("  SpermNet Poster Figure Generator")
    print("═" * 60)
    print(f"  Output: {out_dir}\n")

    generators = [
        ("Fig 1 – Pipeline Architecture", fig1_pipeline_diagram),
        ("Fig 2 – Cohort Motility Bars", fig2_cohort_motility),
        ("Fig 3 – Kinematic Violin Plots", fig3_kinematic_violins),
        ("Fig 4 – GT Correlation Scatter", fig4_gt_correlation),
        ("Fig 5 – Temporal Dynamics", fig5_temporal_dynamics),
        ("Fig 6 – Markov Transitions", fig6_markov_transitions),
        ("Fig 7 – Model Comparison", fig7_model_comparison),
        ("Fig 8 – WHO Compliance", fig8_who_compliance),
    ]

    for name, func in generators:
        print(f"  Generating {name} …")
        try:
            func(out_dir)
        except Exception as exc:
            print(f"  ✗ {name} failed: {exc}")

    print(f"\n{'═' * 60}")
    print(f"  Done – {len(list(out_dir.glob('*.png')))} figures in {out_dir}")
    print("═" * 60)


if __name__ == "__main__":
    main()
